name: Android

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Gluon's GraalVM
      uses: gluonhq/setup-graalvm@master
      with:
        graalvm: '22.1.0.1-Final'
        jdk: 'java17'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android NDK
      run: sdkmanager "ndk;25.1.8937393"

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses

    - name: Install native libraries
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

    - name: Build Android App
      run: chmod +x mvnw && ./mvnw -X -e -Pandroid gluonfx:build gluonfx:package

    - name: Make staging directory
      run: mkdir -p staging

    - name: Copy output
      run: cp target/gluonfx/aarch64-android/gvm/*.aab staging/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Android-Package
        path: staging
